# Generated by Django 3.1.7 on 2021-03-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('categorie1', 'categorie1'), ('categorie2', 'categorie2'), ('categorie3', 'categorie3'), ('categorie4', 'categorie4')], max_length=30)),
                ('departament', models.CharField(choices=[('IT', 'IT'), ('Finante', 'Finante'), ('Contabilitate', 'Contabilitate'), ('Support', 'Support')], max_length=50)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
