# Generated by Django 3.1.7 on 2021-03-22 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=220, unique=True),
            preserve_default=False,
        ),
    ]
